apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lb-demos
  name: lb-demo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lb-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lb-demo-app
    spec:
      containers:
        - name: lb-demo-app
          image: 463113836977.dkr.ecr.ap-south-1.amazonaws.com/lb-demos/demo1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              protocol: "TCP"
      nodeSelector:
        role: web
---
apiVersion: v1
kind: Service
metadata:
  name: lb-demo-app
  namespace: lb-demos
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: lb-demo-app
